### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by grascovit** [mploureno/challenge1#12]
`app/views/clients/index.html.erb:2`
Could be simplified to <% unless Client.exists? %>

`app/views/clients/index.html.erb:8`
`client.last_name[0]` can be a problem if `last_name` is null in the database

The `first_name` and `last_name` from User model are not being persisted in the database. You probably need to permit these 2 params following [this](https://github.com/heartcombo/devise#strong-parameters)

The `password` column added later to the User model in a migration is not being used.

Very good structure for SCSS files :1st_place_medal: 

Clean and concise Rails code overall :100:

**Comment by mploureno** [comment]
I think it's all right now. Thank you, hon :call_me_hand:
